config/routes.rb
Rails.application.routes.draw do
  resources :man_with_animals
  resources :animals
  resources :men
	root 'man_with_animals#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/animal.rb
class Animal < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/man.rb
class Man < ApplicationRecord
end

app/models/man_with_animal.rb
class ManWithAnimal < ApplicationRecord
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: [:show, :edit, :update, :destroy]

  # GET /animals
  # GET /animals.json
  def index
    @animals = Animal.all
  end

  # GET /animals/1
  # GET /animals/1.json
  def show
  end

  # GET /animals/new
  def new
    @animal = Animal.new
  end

  # GET /animals/1/edit
  def edit
  end

  # POST /animals
  # POST /animals.json
  def create
    @animal = Animal.new(animal_params)

    respond_to do |format|
      if @animal.save
        format.html { redirect_to @animal, notice: 'Animal was successfully created.' }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/1
  # PATCH/PUT /animals/1.json
  def update
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to @animal, notice: 'Animal was successfully updated.' }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1
  # DELETE /animals/1.json
  def destroy
    @animal.destroy
    respond_to do |format|
      format.html { redirect_to animals_url, notice: 'Animal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def animal_params
      params.require(:animal).permit(:view)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/man_with_animals_controller.rb
class ManWithAnimalsController < ApplicationController
  before_action :set_man_with_animal, only: [:show, :edit, :update, :destroy]

  # GET /man_with_animals
  # GET /man_with_animals.json
  def index
    @man_with_animals = ManWithAnimal.all
  end

  # GET /man_with_animals/1
  # GET /man_with_animals/1.json
  def show
  end

  # GET /man_with_animals/new
  def new
    @man_with_animal = ManWithAnimal.new
  end

  # GET /man_with_animals/1/edit
  def edit
  end

  # POST /man_with_animals
  # POST /man_with_animals.json
  def create
    @man_with_animal = ManWithAnimal.new(man_with_animal_params)

    respond_to do |format|
      if @man_with_animal.save
        format.html { redirect_to @man_with_animal, notice: 'Man with animal was successfully created.' }
        format.json { render :show, status: :created, location: @man_with_animal }
      else
        format.html { render :new }
        format.json { render json: @man_with_animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /man_with_animals/1
  # PATCH/PUT /man_with_animals/1.json
  def update
    respond_to do |format|
      if @man_with_animal.update(man_with_animal_params)
        format.html { redirect_to @man_with_animal, notice: 'Man with animal was successfully updated.' }
        format.json { render :show, status: :ok, location: @man_with_animal }
      else
        format.html { render :edit }
        format.json { render json: @man_with_animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /man_with_animals/1
  # DELETE /man_with_animals/1.json
  def destroy
    @man_with_animal.destroy
    respond_to do |format|
      format.html { redirect_to man_with_animals_url, notice: 'Man with animal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_man_with_animal
      @man_with_animal = ManWithAnimal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def man_with_animal_params
      params.require(:man_with_animal).permit(:man, :animal)
    end
end

app/controllers/men_controller.rb
class MenController < ApplicationController
  before_action :set_man, only: [ :show, :edit , :update, :destroy]
  before_action :update_list_my_animals, only: [ :update, :destroy, :create]

  # GET /men
  # GET /men.json
  def index
    @men = Man.all
  end

  # GET /men/1
  # GET /men/1.json
  def show
  end

  # GET /men/new
  def new
    @man = Man.new
    @old_list = []
  end

  # GET /men/1/edit
  def edit
  end

  # POST /men
  # POST /men.json
  def create
    respond_to do |format|
      if @man.save
        format.html { redirect_to @man, notice: 'Man was successfully created.' }
        format.json { render :show, status: :created, location: @man }
      else
        format.html { render :new }
        format.json { render json: @man.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /men/1
  # PATCH/PUT /men/1.json
  def update
    respond_to do |format|
      if @man.update(man_params)
        format.html { redirect_to @man, notice: 'Man was successfully updated.' }
        format.json { render :show, status: :ok, location: @man }
      else
        format.html { render :edit }
        format.json { render json: @man.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /men/1
  # DELETE /men/1.json
  def destroy
    @man.destroy
    respond_to do |format|
      format.html { redirect_to men_url, notice: 'Man was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_man
    @man = Man.find(params[:id])
    # ids_of_my_animals
    @old_list = []
    ManWithAnimal.where(man: @man.id).each do |pair|
      @old_list.push(pair.animal)
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def man_params
    params.require(:man).permit(:name)
  end

  def update_list_my_animals
    if (action_name == 'create')
      @man = Event.new(man_params)
      @man.save
      @old_list = []
    else
      set_man
    end
    # "wodr" need == checkbox I parametr without []
    if (action_name == 'destroy' || params["animal_ids"].nil?)
      ManWithAnimal.where(man: @man.id).each do |one_pair|
        one_pair.destroy
      end
    else
      new_list = []
      params["animal_ids"].each do |animal_id|
        new_list << animal_id.to_i
      end
      create_list =  new_list - @old_list
      delete_list = @old_list -  new_list
      # when you have some problems, un commented this lines
      # puts "old_list is #{@old_list}"
      # puts "new_list is #{new_list}"
      # puts "create_list is #{create_list}"
      # puts "delete_list is #{delete_list}"
      delete_list.each do |animal_id|
        ManWithAnimal.where(man: @man.id, animal: animal_id).each do |one_pair|
          one_pair.destroy
        end
      end
      create_list.each do |animal_id|
        one_pair = ManWithAnimal.new
        one_pair.animal = animal_id
        one_pair.man = @man.id
        one_pair.save
      end
    end
  end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/man_with_animals_helper.rb
module ManWithAnimalsHelper
end

app/helpers/men_helper.rb
module MenHelper
end

app/views/animals/_form.html.erb
<%= form_with(model: animal, local: true) do |form| %>
  <% if animal.errors.any? %><div id="error_explanation">
      <h2><%= pluralize(animal.errors.count, "error") %> prohibited this animal from being saved:</h2>
      <ul><% animal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %></ul>
  </div><% end %>

  <div class="field"><%= form.label :view %><%= form.text_field :view, id: :animal_view %></div>
  <div class="actions"><%= form.submit %></div>
<% end %>

app/views/animals/edit.html.erb
<h1>Editing Animal</h1>
<%= render 'form', animal: @animal %>
<%= link_to 'Show', @animal %>
<%= link_to 'Back', animals_path %>

app/views/animals/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Animals</h1>
<table>
  <thead><tr>
    <th>View</th>
    <th colspan="3"></th>
  </tr></thead>
  <tbody><% @animals.each do |animal| %><tr>
        <td><%= animal.view %></td>
        <td><%= link_to 'Show', animal %></td>
        <td><%= link_to 'Edit', edit_animal_path(animal) %></td>
        <td><%= link_to 'Destroy', animal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr><% end %></tbody>
</table>
<br><%= link_to 'New Animal', new_animal_path %>

app/views/animals/new.html.erb
<h1>New Animal</h1>
<%= render 'form', animal: @animal %>
<%= link_to 'Back', animals_path %>

app/views/animals/show.html.erb
<p id="notice"><%= notice %></p>
<p><strong>View:</strong><%= @animal.view %></p>
<%= link_to 'Edit', edit_animal_path(@animal) %>
<%= link_to 'Back', animals_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HomeAnimals</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 				'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <table width="100%"><tbody><tr align="center">
  	<td><%= link_to 'люди', men_path %></td>
  	<td><%= link_to 'домашние животные', man_with_animals_path %></td>
  	<td><%= link_to 'животные', animals_path %></td>
  </tr></tbody></table>
  <hr>
  <%= yield %>
  </body>
</html>

app/views/man_with_animals/_form.html.erb
<%= form_with(model: man_with_animal, local: true) do |form| %>
  <% if man_with_animal.errors.any? %><div id="error_explanation">
    <h2><%= pluralize(man_with_animal.errors.count, "error") %> prohibited this man_with_animal from being saved:</h2>
    <ul><% man_with_animal.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %></ul>
  </div><% end %>
  <div class="field"><%= form.collection_select(:man,       Man.all, :id, :name) %></div>
  <div class="field"><%= form.collection_select(:animal, Animal.all, :id, :view) %></div>
  <div class="actions"><%= form.submit %></div>
<% end %>

app/views/man_with_animals/edit.html.erb
<h1>Editing Man With Animal</h1>
<%= render 'form', man_with_animal: @man_with_animal %>
<%= link_to 'Show', @man_with_animal %>
<%= link_to 'Back', man_with_animals_path %>

app/views/man_with_animals/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Man With Animals</h1>
<table>
  <thead><tr>
    <th>Man</th>
    <th>Animal</th>
    <th colspan="3"></th>
  </tr></thead>
  <tbody><% @man_with_animals.each do |man_with_animal| %><tr>
        <td>
          <% if man_with_animal.man.nil? %>
            <i>error (nil)</i>
          <% else %>
            <%= Man.find(man_with_animal.man).name %>
          <% end %>
        </td>
        <td>
          <% if man_with_animal.animal.nil? %>
            <i>error (nil)</i>
          <% else %>
            <%= Animal.find(man_with_animal.animal).view %>
          <% end %>
        </td>
        <td><%= link_to 'Show', man_with_animal %></td>
        <td><%= link_to 'Edit', edit_man_with_animal_path(man_with_animal) %></td>
        <td><%= link_to 'Destroy', man_with_animal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr><% end %></tbody>
</table>
<br><%= link_to 'New Man With Animal', new_man_with_animal_path %>

app/views/man_with_animals/new.html.erb
<h1>New Man With Animal</h1>
<%= render 'form', man_with_animal: @man_with_animal %>
<%= link_to 'Back', man_with_animals_path %>

app/views/man_with_animals/show.html.erb
<p id="notice"><%= notice %></p>
<p><strong>Man:</strong><%= @man_with_animal.man %></p>
<p><strong>Animal:</strong><%= @man_with_animal.animal %></p>
<%= link_to 'Edit', edit_man_with_animal_path(@man_with_animal) %>
<%= link_to 'Back', man_with_animals_path %>

app/views/men/_form.html.erb
<%= form_with(model: man, local: true) do |form| %>
  <% if man.errors.any? %><div id="error_explanation">
    <h2><%= pluralize(man.errors.count, "error") %> prohibited this man from being saved:</h2>
    <ul><% man.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %></ul>
  </div><% end %>
  <div class="field"><%= form.label :name %><%= form.text_field :name, id: :man_name %></div>
  <p>Список животных</p>
  <% Animal.all.each do |one_animal| %>
    <!--check_box_tag(name, value = "1", checked = false, options = {}) -->
    <%= check_box_tag("animal_ids[]" , one_animal.id, @old_list.include?(one_animal.id) )%>
    <%= one_animal.view %>
    <br>
  <% end %>
  <div class="actions"><%= form.submit %></div>
<% end %>

app/views/men/edit.html.erb
<h1>Editing Man</h1>
<%= render 'form', man: @man %>
<%= link_to 'Show', @man %>
<%= link_to 'Back', men_path %>

app/views/men/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Men</h1>
<table>
  <thead><tr>
    <th>Name</th>
    <th colspan="3"></th>
  </tr></thead>
  <tbody><% @men.each do |man| %><tr>
        <td><%= man.name %></td>
        <td><%= link_to 'Show', man %></td>
        <td><%= link_to 'Edit', edit_man_path(man) %></td>
        <td><%= link_to 'Destroy', man, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr><% end %></tbody>
</table>
<br><%= link_to 'New Man', new_man_path %>

app/views/men/new.html.erb
<h1>New Man</h1>
<%= render 'form', man: @man %>
<%= link_to 'Back', men_path %>

app/views/men/show.html.erb
<p id="notice"><%= notice %></p>
<p><strong>Name:</strong><%= @man.name %></p>
<br><strong>Have animals:</strong>
<% @old_list.each do |animal_id| %>
	<br><%= Animal.find(animal_id).view %>
<% end %>
<%= link_to 'Edit', edit_man_path(@man) %>
<%= link_to 'Back', men_path %>